---------------- MODULE SubagentInitProof ----------------
\* Generated by scripts/gen-proof.mjs. Parameterized safety; views and liveness are TLC checked.
EXTENDS SubagentSystem, TLAPS

THEOREM Init_TypeOK ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => TypeOK
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, TypeOK

THEOREM Init_RootFixed ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => RootFixed
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, RootFixed

THEOREM Init_TreeShape ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => TreeShape
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, TreeShape

THEOREM Init_DepthBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => DepthBound
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, DepthBound

THEOREM Init_AuthorityAttenuation ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => AuthorityAttenuation
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, AuthorityAttenuation

THEOREM Init_NameUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => NameUnique
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, NameUnique

THEOREM Init_WorktreeUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => WorktreeUnique
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, WorktreeUnique

THEOREM Init_WorktreeDeclared ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => WorktreeDeclared
  BY Isa DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, WorktreeDeclared

THEOREM Init_EffectCurrent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => EffectCurrent
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, EffectCurrent

THEOREM Init_EffectIdleOutsideRunning ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => EffectIdleOutsideRunning
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, EffectIdleOutsideRunning

THEOREM Init_TerminalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => TerminalSound
  BY Isa DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, TerminalSound

THEOREM Init_WorktreeRemovalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => WorktreeRemovalSound
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, WorktreeRemovalSound

THEOREM Init_CleanSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => CleanSound
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, CleanSound

THEOREM Init_SeqUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => SeqUnique
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, SeqUnique

THEOREM Init_SeqBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => SeqBound
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, SeqBound

THEOREM Init_LiveChildRunningParent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => LiveChildRunningParent
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, LiveChildRunningParent

THEOREM Init_CancelledNoLiveChild ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => CancelledNoLiveChild
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, CancelledNoLiveChild

THEOREM Init_StaleSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => StaleSound
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, Init, StaleSound

THEOREM InitCore ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE Init => CoreInv
  BY Init_TypeOK, Init_RootFixed, Init_TreeShape, Init_DepthBound, Init_AuthorityAttenuation, Init_NameUnique, Init_WorktreeUnique, Init_WorktreeDeclared, Init_EffectCurrent, Init_EffectIdleOutsideRunning, Init_TerminalSound, Init_WorktreeRemovalSound, Init_CleanSound, Init_SeqUnique, Init_SeqBound, Init_LiveChildRunningParent, Init_CancelledNoLiveChild, Init_StaleSound DEF CoreInv

================================================================
