---------------- MODULE SubagentRemoveWorktreeCoreProof ----------------
\* Generated by scripts/gen-proof.mjs. Parameterized safety; views and liveness are TLC checked.
EXTENDS SubagentSystem, TLAPS

THEOREM RemoveWorktreeCore_Type0 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => status' \in [Agents -> Statuses]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_Type1 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => authority' \in [Agents -> Authorities]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_Type2 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => parent' \in [Agents -> Agents \cup {NoAgent}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_Type3 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => depth' \in [Agents -> 0..MaxDepth]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_Type4 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => name' \in [Agents -> Names \cup {NoName}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_Type5 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => seq' \in [Agents -> 0..MaxSeq]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_Type6 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => gen' \in [Agents -> 0..MaxGen]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_Type7 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => worktree' \in [Agents -> Worktrees \cup {NoWorktree}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_Type8 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => wtState' \in [Agents -> WorktreeStates]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_Type9 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => clean' \in [Agents -> BOOLEAN]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_Type10 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => effect' \in [Agents -> Effects]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_Type11 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => effectGen' \in [Agents -> 0..MaxGen]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_Type12 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => terminal' \in [Agents -> Terminals]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_Type13 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => stale' \in [Agents -> BOOLEAN]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_Type14 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => nextSeq' \in 0..MaxSeq
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_TypeOK ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RemoveWorktree(c) => TypeOK'
  BY RemoveWorktreeCore_Type0, RemoveWorktreeCore_Type1, RemoveWorktreeCore_Type2, RemoveWorktreeCore_Type3, RemoveWorktreeCore_Type4, RemoveWorktreeCore_Type5, RemoveWorktreeCore_Type6, RemoveWorktreeCore_Type7, RemoveWorktreeCore_Type8, RemoveWorktreeCore_Type9, RemoveWorktreeCore_Type10, RemoveWorktreeCore_Type11, RemoveWorktreeCore_Type12, RemoveWorktreeCore_Type13, RemoveWorktreeCore_Type14 DEF TypeOK

THEOREM RemoveWorktreeCore_RootFixed ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RootFixed /\ RemoveWorktree(c) => RootFixed'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RootFixed, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_TreeShape ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ TreeShape /\ RootFixed /\ RemoveWorktree(c) => TreeShape'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, TreeShape, RootFixed, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_DepthBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ DepthBound /\ RemoveWorktree(c) => DepthBound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, DepthBound, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_AuthorityAttenuation ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AuthorityAttenuation /\ TreeShape /\ RemoveWorktree(c) => AuthorityAttenuation'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AuthorityAttenuation, TreeShape, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_NameUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ NameUnique /\ RemoveWorktree(c) => NameUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, NameUnique, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_WorktreeUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeUnique /\ RemoveWorktree(c) => WorktreeUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeUnique, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_WorktreeDeclared ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeDeclared /\ RemoveWorktree(c) => WorktreeDeclared'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeDeclared, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_EffectCurrent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ EffectCurrent /\ RemoveWorktree(c) => EffectCurrent'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, EffectCurrent, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_EffectIdleOutsideRunning ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ EffectIdleOutsideRunning /\ RemoveWorktree(c) => EffectIdleOutsideRunning'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, EffectIdleOutsideRunning, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_TerminalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ TerminalSound /\ RemoveWorktree(c) => TerminalSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, TerminalSound, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_WorktreeRemovalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeRemovalSound /\ WorktreeDeclared /\ RemoveWorktree(c) => WorktreeRemovalSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeRemovalSound, WorktreeDeclared, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_CleanSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ CleanSound /\ WorktreeDeclared /\ RemoveWorktree(c) => CleanSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, CleanSound, WorktreeDeclared, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_SeqUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ SeqUnique /\ SeqBound /\ RemoveWorktree(c) => SeqUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, SeqUnique, SeqBound, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_SeqBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ SeqBound /\ RemoveWorktree(c) => SeqBound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, SeqBound, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_LiveChildRunningParent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ LiveChildRunningParent /\ TreeShape /\ RootFixed /\ RemoveWorktree(c) => LiveChildRunningParent'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, LiveChildRunningParent, TreeShape, RootFixed, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_CancelledNoLiveChild ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ CancelledNoLiveChild /\ TerminalSound /\ RootFixed /\ RemoveWorktree(c) => CancelledNoLiveChild'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, CancelledNoLiveChild, TerminalSound, RootFixed, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore_StaleSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ StaleSound /\ RemoveWorktree(c) => StaleSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, StaleSound, RemoveWorktree, GuardRemoveWorktree

THEOREM RemoveWorktreeCore ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: CoreInv /\ RemoveWorktree(c) => CoreInv'
  BY RemoveWorktreeCore_TypeOK, RemoveWorktreeCore_RootFixed, RemoveWorktreeCore_TreeShape, RemoveWorktreeCore_DepthBound, RemoveWorktreeCore_AuthorityAttenuation, RemoveWorktreeCore_NameUnique, RemoveWorktreeCore_WorktreeUnique, RemoveWorktreeCore_WorktreeDeclared, RemoveWorktreeCore_EffectCurrent, RemoveWorktreeCore_EffectIdleOutsideRunning, RemoveWorktreeCore_TerminalSound, RemoveWorktreeCore_WorktreeRemovalSound, RemoveWorktreeCore_CleanSound, RemoveWorktreeCore_SeqUnique, RemoveWorktreeCore_SeqBound, RemoveWorktreeCore_LiveChildRunningParent, RemoveWorktreeCore_CancelledNoLiveChild, RemoveWorktreeCore_StaleSound DEF CoreInv

================================================================
