---------------- MODULE SubagentWorktreeLostCoreProof ----------------
\* Generated by scripts/gen-proof.mjs. Parameterized safety; views and liveness are TLC checked.
EXTENDS SubagentSystem, TLAPS

THEOREM WorktreeLostCore_Type0 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => status' \in [Agents -> Statuses]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_Type1 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => authority' \in [Agents -> Authorities]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_Type2 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => parent' \in [Agents -> Agents \cup {NoAgent}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_Type3 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => depth' \in [Agents -> 0..MaxDepth]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_Type4 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => name' \in [Agents -> Names \cup {NoName}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_Type5 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => seq' \in [Agents -> 0..MaxSeq]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_Type6 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => gen' \in [Agents -> 0..MaxGen]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_Type7 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => worktree' \in [Agents -> Worktrees \cup {NoWorktree}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_Type8 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => wtState' \in [Agents -> WorktreeStates]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_Type9 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => clean' \in [Agents -> BOOLEAN]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_Type10 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => effect' \in [Agents -> Effects]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_Type11 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => effectGen' \in [Agents -> 0..MaxGen]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_Type12 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => terminal' \in [Agents -> Terminals]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_Type13 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => stale' \in [Agents -> BOOLEAN]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_Type14 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => nextSeq' \in 0..MaxSeq
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_TypeOK ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeLost(c) => TypeOK'
  BY WorktreeLostCore_Type0, WorktreeLostCore_Type1, WorktreeLostCore_Type2, WorktreeLostCore_Type3, WorktreeLostCore_Type4, WorktreeLostCore_Type5, WorktreeLostCore_Type6, WorktreeLostCore_Type7, WorktreeLostCore_Type8, WorktreeLostCore_Type9, WorktreeLostCore_Type10, WorktreeLostCore_Type11, WorktreeLostCore_Type12, WorktreeLostCore_Type13, WorktreeLostCore_Type14 DEF TypeOK

THEOREM WorktreeLostCore_RootFixed ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RootFixed /\ WorktreeLost(c) => RootFixed'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RootFixed, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_TreeShape ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ TreeShape /\ RootFixed /\ WorktreeLost(c) => TreeShape'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, TreeShape, RootFixed, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_DepthBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ DepthBound /\ WorktreeLost(c) => DepthBound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, DepthBound, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_AuthorityAttenuation ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AuthorityAttenuation /\ TreeShape /\ WorktreeLost(c) => AuthorityAttenuation'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AuthorityAttenuation, TreeShape, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_NameUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ NameUnique /\ WorktreeLost(c) => NameUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, NameUnique, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_WorktreeUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeUnique /\ WorktreeLost(c) => WorktreeUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeUnique, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_WorktreeDeclared ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeDeclared /\ WorktreeLost(c) => WorktreeDeclared'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeDeclared, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_EffectCurrent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ EffectCurrent /\ WorktreeLost(c) => EffectCurrent'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, EffectCurrent, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_EffectIdleOutsideRunning ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ EffectIdleOutsideRunning /\ WorktreeLost(c) => EffectIdleOutsideRunning'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, EffectIdleOutsideRunning, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_TerminalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ TerminalSound /\ WorktreeLost(c) => TerminalSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, TerminalSound, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_WorktreeRemovalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeRemovalSound /\ WorktreeDeclared /\ WorktreeLost(c) => WorktreeRemovalSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeRemovalSound, WorktreeDeclared, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_CleanSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ CleanSound /\ WorktreeDeclared /\ WorktreeLost(c) => CleanSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, CleanSound, WorktreeDeclared, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_SeqUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ SeqUnique /\ SeqBound /\ WorktreeLost(c) => SeqUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, SeqUnique, SeqBound, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_SeqBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ SeqBound /\ WorktreeLost(c) => SeqBound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, SeqBound, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_LiveChildRunningParent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ LiveChildRunningParent /\ TreeShape /\ RootFixed /\ WorktreeLost(c) => LiveChildRunningParent'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, LiveChildRunningParent, TreeShape, RootFixed, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_CancelledNoLiveChild ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ CancelledNoLiveChild /\ TerminalSound /\ RootFixed /\ WorktreeLost(c) => CancelledNoLiveChild'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, CancelledNoLiveChild, TerminalSound, RootFixed, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore_StaleSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ StaleSound /\ WorktreeLost(c) => StaleSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, StaleSound, WorktreeLost, GuardWorktreeLost

THEOREM WorktreeLostCore ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: CoreInv /\ WorktreeLost(c) => CoreInv'
  BY WorktreeLostCore_TypeOK, WorktreeLostCore_RootFixed, WorktreeLostCore_TreeShape, WorktreeLostCore_DepthBound, WorktreeLostCore_AuthorityAttenuation, WorktreeLostCore_NameUnique, WorktreeLostCore_WorktreeUnique, WorktreeLostCore_WorktreeDeclared, WorktreeLostCore_EffectCurrent, WorktreeLostCore_EffectIdleOutsideRunning, WorktreeLostCore_TerminalSound, WorktreeLostCore_WorktreeRemovalSound, WorktreeLostCore_CleanSound, WorktreeLostCore_SeqUnique, WorktreeLostCore_SeqBound, WorktreeLostCore_LiveChildRunningParent, WorktreeLostCore_CancelledNoLiveChild, WorktreeLostCore_StaleSound DEF CoreInv

================================================================
