---------------- MODULE SubagentAddWorktreeCoreProof ----------------
\* Generated by scripts/gen-proof.mjs. Parameterized safety; views and liveness are TLC checked.
EXTENDS SubagentSystem, TLAPS

THEOREM AddWorktreeCore_Type0 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => status' \in [Agents -> Statuses]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_Type1 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => authority' \in [Agents -> Authorities]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_Type2 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => parent' \in [Agents -> Agents \cup {NoAgent}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_Type3 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => depth' \in [Agents -> 0..MaxDepth]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_Type4 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => name' \in [Agents -> Names \cup {NoName}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_Type5 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => seq' \in [Agents -> 0..MaxSeq]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_Type6 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => gen' \in [Agents -> 0..MaxGen]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_Type7 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => worktree' \in [Agents -> Worktrees \cup {NoWorktree}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_Type8 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => wtState' \in [Agents -> WorktreeStates]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_Type9 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => clean' \in [Agents -> BOOLEAN]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_Type10 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => effect' \in [Agents -> Effects]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_Type11 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => effectGen' \in [Agents -> 0..MaxGen]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_Type12 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => terminal' \in [Agents -> Terminals]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_Type13 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => stale' \in [Agents -> BOOLEAN]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_Type14 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => nextSeq' \in 0..MaxSeq
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_TypeOK ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AddWorktree(c) => TypeOK'
  BY AddWorktreeCore_Type0, AddWorktreeCore_Type1, AddWorktreeCore_Type2, AddWorktreeCore_Type3, AddWorktreeCore_Type4, AddWorktreeCore_Type5, AddWorktreeCore_Type6, AddWorktreeCore_Type7, AddWorktreeCore_Type8, AddWorktreeCore_Type9, AddWorktreeCore_Type10, AddWorktreeCore_Type11, AddWorktreeCore_Type12, AddWorktreeCore_Type13, AddWorktreeCore_Type14 DEF TypeOK

THEOREM AddWorktreeCore_RootFixed ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RootFixed /\ AddWorktree(c) => RootFixed'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RootFixed, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_TreeShape ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ TreeShape /\ RootFixed /\ AddWorktree(c) => TreeShape'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, TreeShape, RootFixed, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_DepthBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ DepthBound /\ AddWorktree(c) => DepthBound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, DepthBound, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_AuthorityAttenuation ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AuthorityAttenuation /\ TreeShape /\ AddWorktree(c) => AuthorityAttenuation'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AuthorityAttenuation, TreeShape, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_NameUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ NameUnique /\ AddWorktree(c) => NameUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, NameUnique, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_WorktreeUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeUnique /\ AddWorktree(c) => WorktreeUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeUnique, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_WorktreeDeclared ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeDeclared /\ AddWorktree(c) => WorktreeDeclared'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeDeclared, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_EffectCurrent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ EffectCurrent /\ AddWorktree(c) => EffectCurrent'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, EffectCurrent, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_EffectIdleOutsideRunning ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ EffectIdleOutsideRunning /\ AddWorktree(c) => EffectIdleOutsideRunning'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, EffectIdleOutsideRunning, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_TerminalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ TerminalSound /\ AddWorktree(c) => TerminalSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, TerminalSound, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_WorktreeRemovalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeRemovalSound /\ WorktreeDeclared /\ AddWorktree(c) => WorktreeRemovalSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeRemovalSound, WorktreeDeclared, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_CleanSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ CleanSound /\ WorktreeDeclared /\ AddWorktree(c) => CleanSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, CleanSound, WorktreeDeclared, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_SeqUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ SeqUnique /\ SeqBound /\ AddWorktree(c) => SeqUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, SeqUnique, SeqBound, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_SeqBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ SeqBound /\ AddWorktree(c) => SeqBound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, SeqBound, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_LiveChildRunningParent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ LiveChildRunningParent /\ TreeShape /\ RootFixed /\ AddWorktree(c) => LiveChildRunningParent'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, LiveChildRunningParent, TreeShape, RootFixed, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_CancelledNoLiveChild ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ CancelledNoLiveChild /\ TerminalSound /\ RootFixed /\ AddWorktree(c) => CancelledNoLiveChild'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, CancelledNoLiveChild, TerminalSound, RootFixed, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore_StaleSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ StaleSound /\ AddWorktree(c) => StaleSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, StaleSound, AddWorktree, GuardAddWorktree

THEOREM AddWorktreeCore ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: CoreInv /\ AddWorktree(c) => CoreInv'
  BY AddWorktreeCore_TypeOK, AddWorktreeCore_RootFixed, AddWorktreeCore_TreeShape, AddWorktreeCore_DepthBound, AddWorktreeCore_AuthorityAttenuation, AddWorktreeCore_NameUnique, AddWorktreeCore_WorktreeUnique, AddWorktreeCore_WorktreeDeclared, AddWorktreeCore_EffectCurrent, AddWorktreeCore_EffectIdleOutsideRunning, AddWorktreeCore_TerminalSound, AddWorktreeCore_WorktreeRemovalSound, AddWorktreeCore_CleanSound, AddWorktreeCore_SeqUnique, AddWorktreeCore_SeqBound, AddWorktreeCore_LiveChildRunningParent, AddWorktreeCore_CancelledNoLiveChild, AddWorktreeCore_StaleSound DEF CoreInv

================================================================
