---------------- MODULE SubagentCompleteCoreProof ----------------
\* Generated by scripts/gen-proof.mjs. Parameterized safety; views and liveness are TLC checked.
EXTENDS SubagentSystem, TLAPS

THEOREM CompleteCore_Type0 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => status' \in [Agents -> Statuses]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_Type1 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => authority' \in [Agents -> Authorities]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_Type2 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => parent' \in [Agents -> Agents \cup {NoAgent}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_Type3 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => depth' \in [Agents -> 0..MaxDepth]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_Type4 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => name' \in [Agents -> Names \cup {NoName}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_Type5 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => seq' \in [Agents -> 0..MaxSeq]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_Type6 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => gen' \in [Agents -> 0..MaxGen]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_Type7 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => worktree' \in [Agents -> Worktrees \cup {NoWorktree}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_Type8 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => wtState' \in [Agents -> WorktreeStates]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_Type9 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => clean' \in [Agents -> BOOLEAN]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_Type10 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => effect' \in [Agents -> Effects]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_Type11 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => effectGen' \in [Agents -> 0..MaxGen]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_Type12 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => terminal' \in [Agents -> Terminals]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_Type13 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => stale' \in [Agents -> BOOLEAN]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_Type14 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => nextSeq' \in 0..MaxSeq
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_TypeOK ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ Complete(c) => TypeOK'
  BY CompleteCore_Type0, CompleteCore_Type1, CompleteCore_Type2, CompleteCore_Type3, CompleteCore_Type4, CompleteCore_Type5, CompleteCore_Type6, CompleteCore_Type7, CompleteCore_Type8, CompleteCore_Type9, CompleteCore_Type10, CompleteCore_Type11, CompleteCore_Type12, CompleteCore_Type13, CompleteCore_Type14 DEF TypeOK

THEOREM CompleteCore_RootFixed ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ RootFixed /\ Complete(c) => RootFixed'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RootFixed, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_TreeShape ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ TreeShape /\ RootFixed /\ Complete(c) => TreeShape'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, TreeShape, RootFixed, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_DepthBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ DepthBound /\ Complete(c) => DepthBound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, DepthBound, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_AuthorityAttenuation ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ AuthorityAttenuation /\ TreeShape /\ Complete(c) => AuthorityAttenuation'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AuthorityAttenuation, TreeShape, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_NameUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ NameUnique /\ Complete(c) => NameUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, NameUnique, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_WorktreeUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeUnique /\ Complete(c) => WorktreeUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeUnique, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_WorktreeDeclared ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeDeclared /\ Complete(c) => WorktreeDeclared'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeDeclared, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_EffectCurrent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ EffectCurrent /\ Complete(c) => EffectCurrent'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, EffectCurrent, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_EffectIdleOutsideRunning ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ EffectIdleOutsideRunning /\ Complete(c) => EffectIdleOutsideRunning'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, EffectIdleOutsideRunning, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_TerminalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ TerminalSound /\ Complete(c) => TerminalSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, TerminalSound, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_WorktreeRemovalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ WorktreeRemovalSound /\ WorktreeDeclared /\ Complete(c) => WorktreeRemovalSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeRemovalSound, WorktreeDeclared, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_CleanSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ CleanSound /\ WorktreeDeclared /\ Complete(c) => CleanSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, CleanSound, WorktreeDeclared, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_SeqUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ SeqUnique /\ SeqBound /\ Complete(c) => SeqUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, SeqUnique, SeqBound, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_SeqBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ SeqBound /\ Complete(c) => SeqBound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, SeqBound, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_LiveChildRunningParent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ LiveChildRunningParent /\ TreeShape /\ RootFixed /\ Complete(c) => LiveChildRunningParent'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, LiveChildRunningParent, TreeShape, RootFixed, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_CancelledNoLiveChild ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ CancelledNoLiveChild /\ TerminalSound /\ RootFixed /\ Complete(c) => CancelledNoLiveChild'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, CancelledNoLiveChild, TerminalSound, RootFixed, Complete, GuardComplete, GuardLive

THEOREM CompleteCore_StaleSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: TypeOK /\ StaleSound /\ Complete(c) => StaleSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, StaleSound, Complete, GuardComplete, GuardLive

THEOREM CompleteCore ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents: CoreInv /\ Complete(c) => CoreInv'
  BY CompleteCore_TypeOK, CompleteCore_RootFixed, CompleteCore_TreeShape, CompleteCore_DepthBound, CompleteCore_AuthorityAttenuation, CompleteCore_NameUnique, CompleteCore_WorktreeUnique, CompleteCore_WorktreeDeclared, CompleteCore_EffectCurrent, CompleteCore_EffectIdleOutsideRunning, CompleteCore_TerminalSound, CompleteCore_WorktreeRemovalSound, CompleteCore_CleanSound, CompleteCore_SeqUnique, CompleteCore_SeqBound, CompleteCore_LiveChildRunningParent, CompleteCore_CancelledNoLiveChild, CompleteCore_StaleSound DEF CoreInv

================================================================
