---------------- MODULE SubagentProbeWorktreeCoreProof ----------------
\* Generated by scripts/gen-proof.mjs. Parameterized safety; views and liveness are TLC checked.
EXTENDS SubagentSystem, TLAPS

THEOREM ProbeWorktreeCore_Type0 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => status' \in [Agents -> Statuses]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_Type1 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => authority' \in [Agents -> Authorities]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_Type2 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => parent' \in [Agents -> Agents \cup {NoAgent}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_Type3 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => depth' \in [Agents -> 0..MaxDepth]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_Type4 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => name' \in [Agents -> Names \cup {NoName}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_Type5 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => seq' \in [Agents -> 0..MaxSeq]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_Type6 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => gen' \in [Agents -> 0..MaxGen]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_Type7 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => worktree' \in [Agents -> Worktrees \cup {NoWorktree}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_Type8 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => wtState' \in [Agents -> WorktreeStates]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_Type9 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => clean' \in [Agents -> BOOLEAN]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_Type10 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => effect' \in [Agents -> Effects]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_Type11 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => effectGen' \in [Agents -> 0..MaxGen]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_Type12 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => terminal' \in [Agents -> Terminals]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_Type13 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => stale' \in [Agents -> BOOLEAN]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_Type14 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => nextSeq' \in 0..MaxSeq
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_TypeOK ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ ProbeWorktree(c, healthy) => TypeOK'
  BY ProbeWorktreeCore_Type0, ProbeWorktreeCore_Type1, ProbeWorktreeCore_Type2, ProbeWorktreeCore_Type3, ProbeWorktreeCore_Type4, ProbeWorktreeCore_Type5, ProbeWorktreeCore_Type6, ProbeWorktreeCore_Type7, ProbeWorktreeCore_Type8, ProbeWorktreeCore_Type9, ProbeWorktreeCore_Type10, ProbeWorktreeCore_Type11, ProbeWorktreeCore_Type12, ProbeWorktreeCore_Type13, ProbeWorktreeCore_Type14 DEF TypeOK

THEOREM ProbeWorktreeCore_RootFixed ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ RootFixed /\ ProbeWorktree(c, healthy) => RootFixed'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RootFixed, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_TreeShape ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ TreeShape /\ RootFixed /\ ProbeWorktree(c, healthy) => TreeShape'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, TreeShape, RootFixed, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_DepthBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ DepthBound /\ ProbeWorktree(c, healthy) => DepthBound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, DepthBound, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_AuthorityAttenuation ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ AuthorityAttenuation /\ TreeShape /\ ProbeWorktree(c, healthy) => AuthorityAttenuation'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AuthorityAttenuation, TreeShape, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_NameUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ NameUnique /\ ProbeWorktree(c, healthy) => NameUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, NameUnique, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_WorktreeUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ WorktreeUnique /\ ProbeWorktree(c, healthy) => WorktreeUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeUnique, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_WorktreeDeclared ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ WorktreeDeclared /\ ProbeWorktree(c, healthy) => WorktreeDeclared'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeDeclared, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_EffectCurrent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ EffectCurrent /\ ProbeWorktree(c, healthy) => EffectCurrent'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, EffectCurrent, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_EffectIdleOutsideRunning ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ EffectIdleOutsideRunning /\ ProbeWorktree(c, healthy) => EffectIdleOutsideRunning'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, EffectIdleOutsideRunning, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_TerminalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ TerminalSound /\ ProbeWorktree(c, healthy) => TerminalSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, TerminalSound, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_WorktreeRemovalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ WorktreeRemovalSound /\ WorktreeDeclared /\ ProbeWorktree(c, healthy) => WorktreeRemovalSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeRemovalSound, WorktreeDeclared, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_CleanSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ CleanSound /\ WorktreeDeclared /\ ProbeWorktree(c, healthy) => CleanSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, CleanSound, WorktreeDeclared, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_SeqUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ SeqUnique /\ SeqBound /\ ProbeWorktree(c, healthy) => SeqUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, SeqUnique, SeqBound, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_SeqBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ SeqBound /\ ProbeWorktree(c, healthy) => SeqBound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, SeqBound, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_LiveChildRunningParent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ LiveChildRunningParent /\ TreeShape /\ RootFixed /\ ProbeWorktree(c, healthy) => LiveChildRunningParent'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, LiveChildRunningParent, TreeShape, RootFixed, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_CancelledNoLiveChild ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ CancelledNoLiveChild /\ TerminalSound /\ RootFixed /\ ProbeWorktree(c, healthy) => CancelledNoLiveChild'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, CancelledNoLiveChild, TerminalSound, RootFixed, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore_StaleSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: TypeOK /\ StaleSound /\ ProbeWorktree(c, healthy) => StaleSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, StaleSound, ProbeWorktree, GuardProbeWorktree

THEOREM ProbeWorktreeCore ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A c \in Agents, healthy \in BOOLEAN: CoreInv /\ ProbeWorktree(c, healthy) => CoreInv'
  BY ProbeWorktreeCore_TypeOK, ProbeWorktreeCore_RootFixed, ProbeWorktreeCore_TreeShape, ProbeWorktreeCore_DepthBound, ProbeWorktreeCore_AuthorityAttenuation, ProbeWorktreeCore_NameUnique, ProbeWorktreeCore_WorktreeUnique, ProbeWorktreeCore_WorktreeDeclared, ProbeWorktreeCore_EffectCurrent, ProbeWorktreeCore_EffectIdleOutsideRunning, ProbeWorktreeCore_TerminalSound, ProbeWorktreeCore_WorktreeRemovalSound, ProbeWorktreeCore_CleanSound, ProbeWorktreeCore_SeqUnique, ProbeWorktreeCore_SeqBound, ProbeWorktreeCore_LiveChildRunningParent, ProbeWorktreeCore_CancelledNoLiveChild, ProbeWorktreeCore_StaleSound DEF CoreInv

================================================================
