---------------- MODULE SubagentDispatchCoreProof ----------------
\* Generated by scripts/gen-proof.mjs. Parameterized safety; views and liveness are TLC checked.
EXTENDS SubagentSystem, TLAPS

THEOREM DispatchCore_Type0 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => status' \in [Agents -> Statuses]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_Type1 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => authority' \in [Agents -> Authorities]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_Type2 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => parent' \in [Agents -> Agents \cup {NoAgent}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_Type3 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => depth' \in [Agents -> 0..MaxDepth]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_Type4 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => name' \in [Agents -> Names \cup {NoName}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_Type5 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => seq' \in [Agents -> 0..MaxSeq]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_Type6 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: gen \in [Agents -> 0..MaxGen] /\ Dispatch(d, c, n, w, auth) => gen' \in [Agents -> 0..MaxGen]
  BY Isa DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_Type7 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => worktree' \in [Agents -> Worktrees \cup {NoWorktree}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_Type8 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => wtState' \in [Agents -> WorktreeStates]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_Type9 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => clean' \in [Agents -> BOOLEAN]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_Type10 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => effect' \in [Agents -> Effects]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_Type11 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => effectGen' \in [Agents -> 0..MaxGen]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_Type12 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => terminal' \in [Agents -> Terminals]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_Type13 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => stale' \in [Agents -> BOOLEAN]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_Type14 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => nextSeq' \in 0..MaxSeq
  BY Isa DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_TypeOK ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ Dispatch(d, c, n, w, auth) => TypeOK'
  BY DispatchCore_Type0, DispatchCore_Type1, DispatchCore_Type2, DispatchCore_Type3, DispatchCore_Type4, DispatchCore_Type5, DispatchCore_Type6, DispatchCore_Type7, DispatchCore_Type8, DispatchCore_Type9, DispatchCore_Type10, DispatchCore_Type11, DispatchCore_Type12, DispatchCore_Type13, DispatchCore_Type14 DEF TypeOK

THEOREM DispatchCore_Root0 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ RootFixed /\ Dispatch(d, c, n, w, auth) => (status[Root] = "running")'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RootFixed, Dispatch, GuardDispatch

THEOREM DispatchCore_Root1 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ RootFixed /\ Dispatch(d, c, n, w, auth) => (parent[Root] = NoAgent)'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RootFixed, Dispatch, GuardDispatch

THEOREM DispatchCore_Root2 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ RootFixed /\ Dispatch(d, c, n, w, auth) => (depth[Root] = 0)'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RootFixed, Dispatch, GuardDispatch

THEOREM DispatchCore_Root3 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ RootFixed /\ Dispatch(d, c, n, w, auth) => (name[Root] = NoName)'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RootFixed, Dispatch, GuardDispatch

THEOREM DispatchCore_Root4 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ RootFixed /\ Dispatch(d, c, n, w, auth) => (worktree[Root] = NoWorktree)'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RootFixed, Dispatch, GuardDispatch

THEOREM DispatchCore_Root5 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ RootFixed /\ Dispatch(d, c, n, w, auth) => (effect[Root] = "idle")'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RootFixed, Dispatch, GuardDispatch

THEOREM DispatchCore_Root6 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ RootFixed /\ Dispatch(d, c, n, w, auth) => (terminal[Root] = "none")'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RootFixed, Dispatch, GuardDispatch

THEOREM DispatchCore_Root7 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ RootFixed /\ Dispatch(d, c, n, w, auth) => authority'[Root] = authority[Root]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Present, ChildOf, Children, LiveChildren, TypeOK, Dispatch, GuardDispatch

THEOREM DispatchCore_RootFixed ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ RootFixed /\ Dispatch(d, c, n, w, auth) => RootFixed'
  BY DispatchCore_Root0, DispatchCore_Root1, DispatchCore_Root2, DispatchCore_Root3, DispatchCore_Root4, DispatchCore_Root5, DispatchCore_Root6, DispatchCore_Root7 DEF RootFixed

THEOREM DispatchCore_TreeShape ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ TreeShape /\ RootFixed /\ Dispatch(d, c, n, w, auth) => TreeShape'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, TreeShape, RootFixed, Dispatch, GuardDispatch

THEOREM DispatchCore_DepthBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ DepthBound /\ Dispatch(d, c, n, w, auth) => DepthBound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, DepthBound, Dispatch, GuardDispatch

THEOREM DispatchCore_AuthorityAttenuation ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ AuthorityAttenuation /\ TreeShape /\ Dispatch(d, c, n, w, auth) => AuthorityAttenuation'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AuthorityAttenuation, TreeShape, Dispatch, GuardDispatch

THEOREM DispatchCore_NameUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ NameUnique /\ Dispatch(d, c, n, w, auth) => NameUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, NameUnique, Dispatch, GuardDispatch

THEOREM DispatchCore_WorktreeUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ WorktreeUnique /\ Dispatch(d, c, n, w, auth) => WorktreeUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeUnique, Dispatch, GuardDispatch

THEOREM DispatchCore_WorktreeDeclared ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ WorktreeDeclared /\ Dispatch(d, c, n, w, auth) => WorktreeDeclared'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeDeclared, Dispatch, GuardDispatch

THEOREM DispatchCore_EffectCurrent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ EffectCurrent /\ Dispatch(d, c, n, w, auth) => EffectCurrent'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, EffectCurrent, Dispatch, GuardDispatch

THEOREM DispatchCore_EffectIdleOutsideRunning ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ EffectIdleOutsideRunning /\ Dispatch(d, c, n, w, auth) => EffectIdleOutsideRunning'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, EffectIdleOutsideRunning, Dispatch, GuardDispatch

THEOREM DispatchCore_TerminalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ TerminalSound /\ Dispatch(d, c, n, w, auth) => TerminalSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, TerminalSound, Dispatch, GuardDispatch

THEOREM DispatchCore_WorktreeRemovalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ WorktreeRemovalSound /\ WorktreeDeclared /\ Dispatch(d, c, n, w, auth) => WorktreeRemovalSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeRemovalSound, WorktreeDeclared, Dispatch, GuardDispatch

THEOREM DispatchCore_CleanSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ CleanSound /\ WorktreeDeclared /\ Dispatch(d, c, n, w, auth) => CleanSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, CleanSound, WorktreeDeclared, Dispatch, GuardDispatch

THEOREM DispatchCore_SeqUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ SeqUnique /\ SeqBound /\ Dispatch(d, c, n, w, auth) => SeqUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, SeqUnique, SeqBound, Dispatch, GuardDispatch

THEOREM DispatchCore_SeqBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ SeqBound /\ Dispatch(d, c, n, w, auth) => SeqBound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, SeqBound, Dispatch, GuardDispatch

THEOREM DispatchCore_LiveChildRunningParent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ LiveChildRunningParent /\ TreeShape /\ RootFixed /\ Dispatch(d, c, n, w, auth) => LiveChildRunningParent'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, LiveChildRunningParent, TreeShape, RootFixed, Dispatch, GuardDispatch

THEOREM DispatchCore_CancelledNoLiveChild ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ CancelledNoLiveChild /\ TerminalSound /\ RootFixed /\ Dispatch(d, c, n, w, auth) => CancelledNoLiveChild'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, CancelledNoLiveChild, TerminalSound, RootFixed, Dispatch, GuardDispatch

THEOREM DispatchCore_StaleSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: TypeOK /\ StaleSound /\ Dispatch(d, c, n, w, auth) => StaleSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, StaleSound, Dispatch, GuardDispatch

THEOREM DispatchCore ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A d, c \in Agents, n \in Names, w \in Worktrees \cup {NoWorktree}, auth \in Authorities: CoreInv /\ Dispatch(d, c, n, w, auth) => CoreInv'
  BY DispatchCore_TypeOK, DispatchCore_RootFixed, DispatchCore_TreeShape, DispatchCore_DepthBound, DispatchCore_AuthorityAttenuation, DispatchCore_NameUnique, DispatchCore_WorktreeUnique, DispatchCore_WorktreeDeclared, DispatchCore_EffectCurrent, DispatchCore_EffectIdleOutsideRunning, DispatchCore_TerminalSound, DispatchCore_WorktreeRemovalSound, DispatchCore_CleanSound, DispatchCore_SeqUnique, DispatchCore_SeqBound, DispatchCore_LiveChildRunningParent, DispatchCore_CancelledNoLiveChild, DispatchCore_StaleSound DEF CoreInv

================================================================
