---------------- MODULE SubagentPiCrashCoreProof ----------------
\* Generated by scripts/gen-proof.mjs. Parameterized safety; views and liveness are TLC checked.
EXTENDS SubagentSystem, TLAPS

THEOREM CrashStalePoint ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE \A a \in Agents: stale \in [Agents -> BOOLEAN] => (IF Present(a) /\ a # Root /\ status[a] \in {"dispatched", "running"} THEN TRUE ELSE stale[a]) \in BOOLEAN
  BY IsaM("force") DEF Present

THEOREM CrashStaleRange ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE stale \in [Agents -> BOOLEAN] => [a \in Agents |-> IF Present(a) /\ a # Root /\ status[a] \in {"dispatched", "running"} THEN TRUE ELSE stale[a]] \in [Agents -> BOOLEAN]
  BY CrashStalePoint, Isa DEF Present

THEOREM PiCrashCore_Type0 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => status' \in [Agents -> Statuses]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_Type1 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => authority' \in [Agents -> Authorities]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_Type2 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => parent' \in [Agents -> Agents \cup {NoAgent}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_Type3 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => depth' \in [Agents -> 0..MaxDepth]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_Type4 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => name' \in [Agents -> Names \cup {NoName}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_Type5 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => seq' \in [Agents -> 0..MaxSeq]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_Type6 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => gen' \in [Agents -> 0..MaxGen]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_Type7 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => worktree' \in [Agents -> Worktrees \cup {NoWorktree}]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_Type8 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => wtState' \in [Agents -> WorktreeStates]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_Type9 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => clean' \in [Agents -> BOOLEAN]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_Type10 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => effect' \in [Agents -> Effects]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_Type11 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => effectGen' \in [Agents -> 0..MaxGen]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_Type12 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => terminal' \in [Agents -> Terminals]
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_Type13 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE stale \in [Agents -> BOOLEAN] /\ PiCrash => stale' \in [Agents -> BOOLEAN]
  BY CrashStaleRange DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_Type14 ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => nextSeq' \in 0..MaxSeq
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, PiCrash

THEOREM PiCrashCore_TypeOK ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ PiCrash => TypeOK'
  BY PiCrashCore_Type0, PiCrashCore_Type1, PiCrashCore_Type2, PiCrashCore_Type3, PiCrashCore_Type4, PiCrashCore_Type5, PiCrashCore_Type6, PiCrashCore_Type7, PiCrashCore_Type8, PiCrashCore_Type9, PiCrashCore_Type10, PiCrashCore_Type11, PiCrashCore_Type12, PiCrashCore_Type13, PiCrashCore_Type14 DEF TypeOK

THEOREM PiCrashCore_RootFixed ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ RootFixed /\ PiCrash => RootFixed'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, RootFixed, PiCrash

THEOREM PiCrashCore_TreeShape ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ TreeShape /\ RootFixed /\ PiCrash => TreeShape'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, TreeShape, RootFixed, PiCrash

THEOREM PiCrashCore_DepthBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ DepthBound /\ PiCrash => DepthBound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, DepthBound, PiCrash

THEOREM PiCrashCore_AuthorityAttenuation ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ AuthorityAttenuation /\ TreeShape /\ PiCrash => AuthorityAttenuation'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, AuthorityAttenuation, TreeShape, PiCrash

THEOREM PiCrashCore_NameUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ NameUnique /\ PiCrash => NameUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, NameUnique, PiCrash

THEOREM PiCrashCore_WorktreeUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ WorktreeUnique /\ PiCrash => WorktreeUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeUnique, PiCrash

THEOREM PiCrashCore_WorktreeDeclared ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ WorktreeDeclared /\ PiCrash => WorktreeDeclared'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeDeclared, PiCrash

THEOREM PiCrashCore_EffectCurrent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ EffectCurrent /\ PiCrash => EffectCurrent'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, EffectCurrent, PiCrash

THEOREM PiCrashCore_EffectIdleOutsideRunning ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ EffectIdleOutsideRunning /\ PiCrash => EffectIdleOutsideRunning'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, EffectIdleOutsideRunning, PiCrash

THEOREM PiCrashCore_TerminalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ TerminalSound /\ PiCrash => TerminalSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, TerminalSound, PiCrash

THEOREM PiCrashCore_WorktreeRemovalSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ WorktreeRemovalSound /\ WorktreeDeclared /\ PiCrash => WorktreeRemovalSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, WorktreeRemovalSound, WorktreeDeclared, PiCrash

THEOREM PiCrashCore_CleanSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ CleanSound /\ WorktreeDeclared /\ PiCrash => CleanSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, CleanSound, WorktreeDeclared, PiCrash

THEOREM PiCrashCore_SeqUnique ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ SeqUnique /\ SeqBound /\ PiCrash => SeqUnique'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, SeqUnique, SeqBound, PiCrash

THEOREM PiCrashCore_SeqBound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ SeqBound /\ PiCrash => SeqBound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, SeqBound, PiCrash

THEOREM PiCrashCore_LiveChildRunningParent ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ LiveChildRunningParent /\ TreeShape /\ RootFixed /\ PiCrash => LiveChildRunningParent'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, LiveChildRunningParent, TreeShape, RootFixed, PiCrash

THEOREM PiCrashCore_CancelledNoLiveChild ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ CancelledNoLiveChild /\ TerminalSound /\ RootFixed /\ PiCrash => CancelledNoLiveChild'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, CancelledNoLiveChild, TerminalSound, RootFixed, PiCrash

THEOREM PiCrashCore_StaleSound ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE TypeOK /\ StaleSound /\ PiCrash => StaleSound'
  BY SMT DEF Statuses, Terminals, Effects, WorktreeStates, Authorities, Present, ChildOf, Children, LiveChildren, RootAuthority, NoAuthority, TypeOK, StaleSound, PiCrash

THEOREM PiCrashCore ==
  ASSUME Root \in Agents,
           MaxDepth \in Nat, MaxGen \in Nat, MaxSeq \in Nat,
           NoAgent \notin Agents, NoName \notin Names, NoWorktree \notin Worktrees
  PROVE CoreInv /\ PiCrash => CoreInv'
  BY PiCrashCore_TypeOK, PiCrashCore_RootFixed, PiCrashCore_TreeShape, PiCrashCore_DepthBound, PiCrashCore_AuthorityAttenuation, PiCrashCore_NameUnique, PiCrashCore_WorktreeUnique, PiCrashCore_WorktreeDeclared, PiCrashCore_EffectCurrent, PiCrashCore_EffectIdleOutsideRunning, PiCrashCore_TerminalSound, PiCrashCore_WorktreeRemovalSound, PiCrashCore_CleanSound, PiCrashCore_SeqUnique, PiCrashCore_SeqBound, PiCrashCore_LiveChildRunningParent, PiCrashCore_CancelledNoLiveChild, PiCrashCore_StaleSound DEF CoreInv

================================================================
