// Generated standalone component lemmas, grouped by action to bound TLAPS context.
// The driver checks each module, then the thin temporal assembly. Anonymous
// assumptions are repeated because tlapm does not use module-level ASSUME.
// SMT(v2) (--debug oldsmt) is the primary backend, with small Isabelle fallbacks.
import { writeFileSync } from "node:fs";

const COMPONENTS = [
  "TypeOK",
  "RootFixed",
  "TreeShape",
  "DepthBound",
  "AuthorityAttenuation",
  "NameUnique",
  "WorktreeUnique",
  "WorktreeDeclared",
  "EffectCurrent",
  "EffectIdleOutsideRunning",
  "TerminalSound",
  "WorktreeRemovalSound",
  "CleanSound",
  "SeqUnique",
  "SeqBound",
  "LiveChildRunningParent",
  "CancelledNoLiveChild",
  "StaleSound",
];

const COMP_TYPES = ["Statuses", "Terminals", "Effects", "WorktreeStates", "Authorities"];

const BASE_DEFS = ["Present", "ChildOf", "Children", "LiveChildren", "RootAuthority", "NoAuthority"];

const ASSUME = [
  "ASSUME Root \\in Agents,",
  "         MaxDepth \\in Nat, MaxGen \\in Nat, MaxSeq \\in Nat,",
  "         NoAgent \\notin Agents, NoName \\notin Names, NoWorktree \\notin Worktrees",
];

// One case per action in `Next` order: [name, title, action DEFs, extra types].
const CASES = [
  [
    "DispatchCore",
    "\\A d, c \\in Agents, n \\in Names, w \\in Worktrees \\cup {NoWorktree}, auth \\in Authorities: CoreInv /\\ Dispatch(d, c, n, w, auth)",
    ["Dispatch", "GuardDispatch"],
    ["Authorities"],
  ],
  ["AddWorktreeCore", "\\A c \\in Agents: CoreInv /\\ AddWorktree(c)", ["AddWorktree", "GuardAddWorktree"]],
  ["AdmitCore", "\\A c \\in Agents: CoreInv /\\ Admit(c)", ["Admit", "GuardAdmit"]],
  ["CompleteCore", "\\A c \\in Agents: CoreInv /\\ Complete(c)", ["Complete", "GuardComplete", "GuardLive"]],
  ["FailCore", "\\A c \\in Agents: CoreInv /\\ Fail(c)", ["Fail", "GuardFail", "GuardLive"]],
  ["CancelCore", "\\A c \\in Agents: CoreInv /\\ Cancel(c)", ["Cancel", "GuardCancel"]],
  ["ProbeWorktreeCore", "\\A c \\in Agents, healthy \\in BOOLEAN: CoreInv /\\ ProbeWorktree(c, healthy)", ["ProbeWorktree", "GuardProbeWorktree"]],
  ["RemoveWorktreeCore", "\\A c \\in Agents: CoreInv /\\ RemoveWorktree(c)", ["RemoveWorktree", "GuardRemoveWorktree"]],
  ["WorktreeFoundCore", "\\A c \\in Agents: CoreInv /\\ WorktreeFound(c)", ["WorktreeFound", "GuardWorktreeFound"]],
  ["WorktreeLostCore", "\\A c \\in Agents: CoreInv /\\ WorktreeLost(c)", ["WorktreeLost", "GuardWorktreeLost"]],
  ["ReconcileCore", "\\A c \\in Agents: CoreInv /\\ Reconcile(c)", ["Reconcile", "GuardReconcile"]],
  ["ClearCore", "\\A c \\in Agents: CoreInv /\\ Clear(c)", ["Clear", "GuardClear"]],
  ["PiCrashCore", "CoreInv /\\ PiCrash", ["PiCrash"]],
  ["UnchangedCore", "CoreInv /\\ UNCHANGED vars", ["vars"]],
];


const extras = {
  TreeShape: ["RootFixed"],
  AuthorityAttenuation: ["TreeShape"],
  SeqUnique: ["SeqBound"],
  LiveChildRunningParent: ["TreeShape", "RootFixed"],
  CancelledNoLiveChild: ["TerminalSound", "RootFixed"],
  WorktreeRemovalSound: ["WorktreeDeclared"],
  CleanSound: ["WorktreeDeclared"],
};
let lines = [];
const push = (s = "") => lines.push(s);
function theorem(name, goal, proof) {
  push(`THEOREM ${name} ==`);
  for (const a of ASSUME) push(`  ${a}`);
  push(`  PROVE ${goal}`);
  push(`  ${proof}`);
  push();
}
const types = [
  "status \\in [Agents -> Statuses]", "authority \\in [Agents -> Authorities]",
  "parent \\in [Agents -> Agents \\cup {NoAgent}]", "depth \\in [Agents -> 0..MaxDepth]",
  "name \\in [Agents -> Names \\cup {NoName}]", "seq \\in [Agents -> 0..MaxSeq]",
  "gen \\in [Agents -> 0..MaxGen]", "worktree \\in [Agents -> Worktrees \\cup {NoWorktree}]",
  "wtState \\in [Agents -> WorktreeStates]", "clean \\in [Agents -> BOOLEAN]",
  "effect \\in [Agents -> Effects]", "effectGen \\in [Agents -> 0..MaxGen]",
  "terminal \\in [Agents -> Terminals]", "stale \\in [Agents -> BOOLEAN]", "nextSeq \\in 0..MaxSeq",
];
const modules = [];
function begin(module) {
  modules.push(module);
  lines = [`---------------- MODULE ${module} ----------------`, "\\* Generated by scripts/gen-proof.mjs. Parameterized safety; views and liveness are TLC checked.", "EXTENDS SubagentSystem, TLAPS", ""];
}
function finish(module) {
  push("================================================================");
  writeFileSync(`spec/${module}.tla`, lines.join("\n") + "\n");
}
begin("SubagentInitProof");
for (const c of COMPONENTS) {
  theorem(`Init_${c}`, `Init => ${c}`, `BY ${["TerminalSound", "WorktreeDeclared"].includes(c) ? "Isa" : "SMT"} DEF ${[...COMP_TYPES, ...BASE_DEFS, "Init", c].join(", ")}`);
}
theorem("InitCore", "Init => CoreInv", `BY ${COMPONENTS.map(c => `Init_${c}`).join(", ")} DEF CoreInv`);
finish("SubagentInitProof");
for (const [name, title, actionDefs] of CASES) {
  begin(`Subagent${name}Proof`);
  if (name === "PiCrashCore") {
    theorem("CrashStalePoint", "\\A a \\in Agents: stale \\in [Agents -> BOOLEAN] => (IF Present(a) /\\ a # Root /\\ status[a] \\in {\"dispatched\", \"running\"} THEN TRUE ELSE stale[a]) \\in BOOLEAN", 'BY IsaM("force") DEF Present');
    theorem("CrashStaleRange", "stale \\in [Agents -> BOOLEAN] => [a \\in Agents |-> IF Present(a) /\\ a # Root /\\ status[a] \\in {\"dispatched\", \"running\"} THEN TRUE ELSE stale[a]] \\in [Agents -> BOOLEAN]", "BY CrashStalePoint, Isa DEF Present");
  }
  for (const c of COMPONENTS) {
    const hyp = [...new Set(["TypeOK", c, ...(extras[c] ?? []), ...(name === "ReconcileCore" ? ["StaleSound"] : [])])];
    const goal = title.replace("CoreInv", hyp.join(" /\\ "));
    const defs = [...new Set([...COMP_TYPES, ...BASE_DEFS, ...hyp, ...actionDefs])];
    if (c === "TypeOK") {
      for (const [i, type] of types.entries()) {
        const method = ((name === "DispatchCore" && (i === 6 || i === 14)) || (name === "CancelCore" && i === 6)) ? "Isa" : "SMT";
        theorem(`${name}_Type${i}`, `${(name === "DispatchCore" && i === 6) || (name === "PiCrashCore" && i === 13) ? goal.replace("TypeOK", type) : goal} => ${type.replace(" \\in", "' \\in")}`, `BY ${name === "PiCrashCore" && i === 13 ? "CrashStaleRange" : method} DEF ${defs.join(", ")}`);
      }
      theorem(`${name}_${c}`, `${goal} => ${c}'`, `BY ${types.map((_, i) => `${name}_Type${i}`).join(", ")} DEF TypeOK`);
    } else if (c === "RootFixed" && ["DispatchCore", "ClearCore"].includes(name)) {
      const clauses = ["status[Root] = \"running\"", "parent[Root] = NoAgent", "depth[Root] = 0", "name[Root] = NoName", "worktree[Root] = NoWorktree", "effect[Root] = \"idle\"", "terminal[Root] = \"none\"", "authority[Root] = RootAuthority"];
      for (const [i, clause] of clauses.entries()) {
        const rootGoal = i === 7 ? "authority'[Root] = authority[Root]" : `(${clause})'`;
        const rootDefs = i === 7 ? defs.filter(d => !["RootFixed", "RootAuthority", "NoAuthority", "Authorities"].includes(d)) : defs;
        theorem(`${name}_Root${i}`, `${goal} => ${rootGoal}`, `BY SMT DEF ${rootDefs.join(", ")}`);
      }
      theorem(`${name}_${c}`, `${goal} => ${c}'`, `BY ${clauses.map((_,i) => `${name}_Root${i}`).join(", ")} DEF RootFixed`);
    } else {
      theorem(`${name}_${c}`, `${goal} => ${c}'`, `BY SMT DEF ${defs.join(", ")}`);
    }
  }
  theorem(name, `${title} => CoreInv'`, `BY ${COMPONENTS.map(c => `${name}_${c}`).join(", ")} DEF CoreInv`);
  finish(`Subagent${name}Proof`);
}
lines = ["---------------- MODULE SubagentSystemProof ----------------", "\\* Generated; the driver checks every imported proof module before this assembly.", `EXTENDS ${modules.join(", ")}`, ""];
theorem("NextCore", "CoreInv /\\ [Next]_vars => CoreInv'", `BY ${CASES.map(c => c[0]).join(", ")} DEF Next, vars`);
theorem("SafetyCore", "SafetySpec => []CoreInv", "BY InitCore, NextCore, PTL DEF SafetySpec");
push("=========================================================================");
push();
const output = process.argv[2] ?? "spec/SubagentSystemProof.tla";
writeFileSync(output, lines.join("\n"), "utf8");
console.log(`wrote ${output}`);
